export default placeholderData = [
    {
        id: 1,
        desc: "Starbucks",
        category: "Leisure",
        amount: 3.45,
        curr: "CAD",
        income: false,
        date: new Date() - (1000 * 60 * 60 * (Math.random() * 24 * 30)),
    },
    {
        id: 2,
        desc: "Fanshawe - Tuition",
        category: "Education",
        amount: 8549.99,
        curr: "CAD",
        income: false,
        date: new Date() - (1000 * 60 * 60 * (Math.random() * 24 * 30)),
    },
    {
        id: 3,
        desc: "Uber",
        category: "Services & utilities",
        amount: 12.34,
        curr: "CAD",
        income: false,
        date: new Date() - (1000 * 60 * 60 * (Math.random() * 24 * 30)),
    },
    {
        id: 4,
        desc: "Real Canadian Superstore",
        category: "Groceries",
        amount: 420.69,
        curr: "CAD",
        income: false,
        date: new Date() - (1000 * 60 * 60 * (Math.random() * 24 * 30)),
    },
    {
        id: 5,
        desc: "Apple Canada",
        category: "Income",
        amount: 4780.23,
        curr: "CAD",
        income: false,
        date: new Date() - (1000 * 60 * 60 * (Math.random() * 24 * 30)),
    },
    {
        id: 6,
        desc: "CRA",
        category: "Services & utilities",
        amount: 1234.07,
        curr: "CAD",
        income: false,
        date: new Date() - (1000 * 60 * 60 * (Math.random() * 24 * 30)),
    },
]